spring:
  application:
    name: image-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: ${profile:praia}

eureka:
  instance:
    hostname: localhost
