spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: ${profile:dev}

eureka:
  instance:
    hostname: localhost
