server:
  port: 8086
  servlet:
    context-path: /movie/
spring:
  config:
    import: optional:configserver:http://config:8888/
  application:
    name: movie-service
  cloud:
    config:
      profile: ${profile:dev}
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: root
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
