version: '3.2'

services:

  zipkin-service:
    image: openzipkin/zipkin:2
    container_name: zipkin-service
    ports:
      - 9411:9411

  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672

  db-movie:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuarioAplicacao
      MYSQL_PASSWORD: 123456789Tu
      MYSQL_DATABASE: movie
    ports:
      - 3301:3306

  db-catalogo:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuarioAplicacao
      MYSQL_PASSWORD: 123456789Tu
      MYSQL_DATABASE: catalogo
    ports:
      - 3302:3306

  db-series:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuarioAplicacao
      MYSQL_PASSWORD: 123456789Tu
      MYSQL_DATABASE: series
    ports:
      - 3303:3306
